project:
  type: book
  output-dir: docs

# do not show output of code chunks - outside errors
execute:
  echo: false
warning: false

book:
  title: "Operational Comparison of ANS Performance in Brazil and Europe"
  author: "DECEA Performance Section, EUROCONTROL Performance Review Unit"
  date: 14. April 2024
  date-format: "MMMM YYYY"
  chapters:
  - index.qmd
  - 00_foreword.qmd
  - 00-executive-summary.qmd
  - 01-intro.qmd
  - 02-system_overview.qmd
  - 03-traffic_characterisation.qmd
  - 04-predictability.qmd
  - 05-capacity_and_throughput.qmd
  - 06-efficiency.qmd
# - 07-environment.qmd
  - 08-conclusions.qmd
  - 99-references.qmd
  navbar:
    background: dark
    search: true
    title: false
    logo: "media/EUROCONTROL-logo-standard-rgb.png"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Performance areas"
        menu:
          - text: "{{< iconify fa6-solid th >}}&nbsp;Balanced scorecard"
            href: "https://www.eurocontrol.int/Economics/BalancedScorecard.html"
          - text: "{{< iconify fa6-solid plane-departure >}}&nbsp;Traffic"
            href: traffic.qmd
          - text: "&nbsp;&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Daily traffic dashboard</span>"
            href: "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Service units</span>"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Traffic forecast</span>"
            href: traffic/statfor.qmd
          - text: "{{< iconify fa6-solid calendar >}}&nbsp;Punctuality"
            href: traffic/punctuality.qmd
          - text: "&nbsp;&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Daily punctuality dashboard</span>"
            href: "https://www.eurocontrol.int/Economics/DailyPunctuality-States.html"
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Network punctuality</span>"
            href: traffic/punctuality.qmd#eurocontrol-area-network-view-1
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>State & airport punctuality</span>"
            href: traffic/punctuality.qmd#state-view-1
          - text: "{{< iconify fa6-solid clock >}}&nbsp;En-route & airport delays"
            href: capacity.qmd
          - text: "&nbsp;&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Daily ATFM delays dashboard</span>"
            href: "https://www.eurocontrol.int/Economics/DailyDelay-States.html"
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>En-route ATFM delays</span>"
            href: capacity/atfm_ert.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Airport ATFM delays</span>"
            href: capacity/atfm_apt.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>All-causes delays</span>"
            href: capacity/tot_dly.qmd
          - text: "{{< iconify fa6-solid leaf >}}&nbsp;Efficiency & environment"
            href: efficiency.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>CO<sub>2</sub> emissions</span>"
            href: efficiency/emissions.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Horizontal flight efficiency</span>"
            href: efficiency/hfe.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Vertical flight efficiency</span>"
            href: efficiency/vfe.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Terminal holdings</span>"
            href: efficiency/asma.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Taxi-out</span>"
            href: efficiency/taxiout.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Taxi-in</span>"
            href: efficiency/taxiin.qmd
          - text: "{{< iconify fa6-solid euro-sign >}}&nbsp;Economics"
            href: economics.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>ATM cost-effectiveness (ACE)</span>"
            href: economics/ace-overview.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Unit rates and costs</span>"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteUnitRates.html"
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Service units</span>"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>ANSPs financial dashboard</span>"
            href: economics/finance.qmd
          - text: "&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Standard Inputs for Economic Analyses</span>"
            href: economics/cba.qmd

      - text: "Stakeholder views"
        menu:
          - text: "{{< iconify fa6-solid plane-arrival >}}&nbsp;Airports"
            href: dashboard/stakeholder/airport.qmd
          - text: "{{< iconify fa6-solid compass >}}&nbsp;Air navigation service provider"
            href: dashboard/stakeholder/ansp.qmd
          - text: "{{< iconify fa6-solid globe >}}&nbsp;States"
            href: dashboard/stakeholder/state.qmd

      - text: "Data"
        href: data.qmd

      - text: "Publications"
        href: publications.qmd

      - text: "Reference"
        menu:
          - text: "{{< iconify fa6-solid marker >}}&nbsp;Definitions"
            href: definition.qmd
          - text: "{{< iconify fa6-solid wrench >}}&nbsp;Methodology"
            href: methodology.qmd
          - text: "{{< iconify fa6-solid quote-left >}}&nbsp;Acronyms"
            href: acronym.qmd
          - text: "{{< iconify fa6-solid book >}}&nbsp;Bibliography"
            href: bibliography.qmd

      - text: "Links"
        menu:
          - text: "EUROCONTROL <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://www.eurocontrol.int/"
          - text: "Single European Sky (SES) portal <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://www.eurocontrol.int/prudata/dashboard/"
          - text: "ICAO GANP <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://www4.icao.int/ganpportal/"
          - text: "Connectivity dashboard <i class='fas fa-xs fa-external-link-alt'></i>"
            href: "https://ext.eurocontrol.int/connectivity_web/from"
          - text: "PRC Transformation Strategy"
            href: transformation.qmd
          - text: "PRC Open Performance Data Initiative"
            href: "https://opdi.aero"

      - text: "About"
        menu:
          - text: "About the PRC"
            href: about/prc.qmd
          - text: "About the AIU"
            href: about/aiu.qmd
          - text: "About the PRU"
            href: about/us.qmd
          - text: "Release notes"
            href: post.qmd
          - text: "Disclaimer"
            href: about/disclaimer.qmd
  
appendices:
  - A1-appendix.qmd
  
downloads: [pdf, docx]

#bibliography: book.bib   #, packages.bib]
bibliography: references.bib


format:
  html:
    theme: cosmo
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <style>
          .navbar-logo {
            max-height: 60px;
          }
        </style>
  pdf:
    documentclass: scrreport
    papersize: a4
    fig-pos: 'H'
    geometry:
    - top=30mm
    - right=30mm
    - left=30mm
    - bottom=30mm
    - heightrounded
    include-in-header:
      text: |
        \usepackage{pdfpages}
        \pagenumbering{gobble}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead[L]{\leftmark}
        \fancyhead[R]{}
        \fancyfoot[L]{}

  docx:
    toc: true
    number-sections: true
    highlight-style: github
    fig-dpi: 320

  # epub:
  #    cover-image: cover.png
