project:
  type: book
  output-dir: docs

# do not show output of code chunks - outside errors
execute:
  echo: false
warning: false

book:
  title: "Operational Comparison of ANS Performance in Brazil and Europe"
  author: "DECEA Performance Section, EUROCONTROL Performance Review Unit"
  date: 14. April 2024
  date-format: "MMMM YYYY"
  chapters:
  - index.qmd
  - 00_foreword.qmd
  - 00-executive-summary.qmd
  - 01-intro.qmd
  - 02-system_overview.qmd
  - 03-traffic_characterisation.qmd
  - 04-predictability.qmd
  - 05-capacity_and_throughput.qmd
  - 06-efficiency.qmd
# - 07-environment.qmd
  - 08-conclusions.qmd
  - 99-references.qmd
  navbar:
    background: light
    search: false
    title: false
    logo: "media/EUROCONTROL-logo-standard-rgb.svg"
    right:
      - text: "Home"
        href: "/#/"
      - text: "Performance areas"
        menu:
          - text: "Balanced scorecard"
            href: "https://www.eurocontrol.int/Economics/BalancedScorecard.html"
          - text: "Traffic"
            menu:
              - text: "Daily traffic dashboard"
                href: "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"
              - text: "Service units"
                href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
              - text: "Traffic forecast"
                href: "/traffic/statfor/"
          - text: "Punctuality"
            menu:
              - text: "Daily punctuality dashboard"
                href: "https://www.eurocontrol.int/Economics/DailyPunctuality-States.html"
              - text: "Network punctuality"
                href: "/traffic/punctuality/#eurocontrol-area-network-view-1"
              - text: "State & airport punctuality"
                href: "/traffic/punctuality/#state-view-1"
          - text: "En-route & airport delays"
            menu:
              - text: "Daily ATFM delays dashboard"
                href: "https://www.eurocontrol.int/Economics/DailyDelay-States.html"
              - text: "En-route ATFM delays"
                href: "/capacity/atfm_ert/"
              - text: "Airport ATFM delays"
                href: "/capacity/atfm_apt/"
              - text: "All-causes delays"
                href: "/capacity/tot_dly/"
          - text: "Efficiency & environment"
            menu:
              - text: "CO₂ emissions"
                href: "/efficiency/emissions/"
              - text: "Horizontal flight efficiency"
                href: "/efficiency/hfe/"
              - text: "Vertical flight efficiency"
                href: "/efficiency/vfe/"
              - text: "Terminal holdings"
                href: "/efficiency/asma/"
              - text: "Taxi-out"
                href: "/efficiency/taxiout/"
              - text: "Taxi-in"
                href: "/efficiency/taxiin/"
          - text: "Economics"
            menu:
              - text: "ATM cost-effectiveness (ACE)"
                href: "/economics/ace-overview/"
              - text: "Unit rates and costs"
                href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteUnitRates.html"
              - text: "Service units"
                href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
              - text: "ANSPs financial dashboard"
                href: "/economics/finance/"
              - text: "Standard Inputs for Economic Analyses"
                href: "/economics/cba/"
      - text: "Stakeholder views"
        menu:
          - text: "Airports"
            href: "/dashboard/stakeholder/airport/"
          - text: "Air navigation service provider"
            href: "/dashboard/stakeholder/ansp/"
          - text: "States"
            href: "/dashboard/stakeholder/state/"
      - text: "Data"
        href: "/data/"
      - text: "Publications"
        href: "/publications/"
      - text: "Reference"
        menu:
          - text: "Definitions"
            href: "/definition/"
          - text: "Methodology"
            href: "/methodology/"
          - text: "Acronyms"
            href: "/acronym/"
          - text: "Bibliography"
            href: "/bibliography/"
      - text: "Links"
        menu:
          - text: "EUROCONTROL"
            href: "https://www.eurocontrol.int/"
          - text: "Single European Sky (SES) portal"
            href: "https://www.eurocontrol.int/prudata/dashboard/"
          - text: "ICAO GANP"
            href: "https://www4.icao.int/ganpportal/"
          - text: "Connectivity dashboard"
            href: "https://ext.eurocontrol.int/connectivity_web/from"
          - text: "PRC Transformation Strategy"
            href: "/transformation/"
          - text: "PRC Open Performance Data Initiative"
            href: "https://opdi.aero"
      - text: "About"
        menu:
          - text: "About the PRC"
            href: "/about/prc/"
          - text: "About the AIU"
            href: "/about/aiu/"
          - text: "About the PRU"
            href: "/about/us/"
          - text: "Release notes"
            href: "/post/"
          - text: "Disclaimer"
            href: "/about/disclaimer/"
  
appendices:
  - A1-appendix.qmd
  
downloads: [pdf, docx]

#bibliography: book.bib   #, packages.bib]
bibliography: references.bib


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
    papersize: a4
    fig-pos: 'H'
    geometry:
    - top=30mm
    - right=30mm
    - left=30mm
    - bottom=30mm
    - heightrounded
    include-in-header:
      text: |
        \usepackage{pdfpages}
        \pagenumbering{gobble}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead[L]{\leftmark}
        \fancyhead[R]{}
        \fancyfoot[L]{}

  docx:
    toc: true
    number-sections: true
    highlight-style: github
    fig-dpi: 320

  # epub:
  #    cover-image: cover.png
